package ir.thatsmejavad.backgroundable.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val ao_light_primary = Color(0xFF006E00)
private val ao_light_onPrimary = Color(0xFFFFFFFF)
private val ao_light_primaryContainer = Color(0xFF8DFB77)
private val ao_light_onPrimaryContainer = Color(0xFF002200)
private val ao_light_secondary = Color(0xFF54634D)
private val ao_light_onSecondary = Color(0xFFFFFFFF)
private val ao_light_secondaryContainer = Color(0xFFD7E8CD)
private val ao_light_onSecondaryContainer = Color(0xFF121F0E)
private val ao_light_tertiary = Color(0xFF386568)
private val ao_light_onTertiary = Color(0xFFFFFFFF)
private val ao_light_tertiaryContainer = Color(0xFFBCEBEE)
private val ao_light_onTertiaryContainer = Color(0xFF002022)
private val ao_light_error = Color(0xFFBA1A1A)
private val ao_light_errorContainer = Color(0xFFFFDAD6)
private val ao_light_onError = Color(0xFFFFFFFF)
private val ao_light_onErrorContainer = Color(0xFF410002)
private val ao_light_background = Color(0xFFFCFDF6)
private val ao_light_onBackground = Color(0xFF1A1C18)
private val ao_light_surface = Color(0xFFFCFDF6)
private val ao_light_onSurface = Color(0xFF1A1C18)
private val ao_light_surfaceVariant = Color(0xFFDFE4D7)
private val ao_light_onSurfaceVariant = Color(0xFF43483F)
private val ao_light_outline = Color(0xFF73796E)
private val ao_light_inverseOnSurface = Color(0xFFF1F1EB)
private val ao_light_inverseSurface = Color(0xFF2F312D)
private val ao_light_inversePrimary = Color(0xFF72DE5E)
private val ao_light_surfaceTint = Color(0xFF006E00)
private val ao_light_outlineVariant = Color(0xFFC3C8BC)
private val ao_light_scrim = Color(0xFF000000)

private val ao_dark_primary = Color(0xFF72DE5E)
private val ao_dark_onPrimary = Color(0xFF003A00)
private val ao_dark_primaryContainer = Color(0xFF005300)
private val ao_dark_onPrimaryContainer = Color(0xFF8DFB77)
private val ao_dark_secondary = Color(0xFFBBCBB2)
private val ao_dark_onSecondary = Color(0xFF263422)
private val ao_dark_secondaryContainer = Color(0xFF3C4B37)
private val ao_dark_onSecondaryContainer = Color(0xFFD7E8CD)
private val ao_dark_tertiary = Color(0xFFA0CFD2)
private val ao_dark_onTertiary = Color(0xFF003739)
private val ao_dark_tertiaryContainer = Color(0xFF1E4D50)
private val ao_dark_onTertiaryContainer = Color(0xFFBCEBEE)
private val ao_dark_error = Color(0xFFFFB4AB)
private val ao_dark_errorContainer = Color(0xFF93000A)
private val ao_dark_onError = Color(0xFF690005)
private val ao_dark_onErrorContainer = Color(0xFFFFDAD6)
private val ao_dark_background = Color(0xFF1A1C18)
private val ao_dark_onBackground = Color(0xFFE2E3DC)
private val ao_dark_surface = Color(0xFF1A1C18)
private val ao_dark_onSurface = Color(0xFFE2E3DC)
private val ao_dark_surfaceVariant = Color(0xFF43483F)
private val ao_dark_onSurfaceVariant = Color(0xFFC3C8BC)
private val ao_dark_outline = Color(0xFF8D9387)
private val ao_dark_inverseOnSurface = Color(0xFF1A1C18)
private val ao_dark_inverseSurface = Color(0xFFE2E3DC)
private val ao_dark_inversePrimary = Color(0xFF006E00)
private val ao_dark_surfaceTint = Color(0xFF72DE5E)
private val ao_dark_outlineVariant = Color(0xFF43483F)
private val ao_dark_scrim = Color(0xFF000000)

val aoLightColors = lightColorScheme(
    primary = ao_light_primary,
    onPrimary = ao_light_onPrimary,
    primaryContainer = ao_light_primaryContainer,
    onPrimaryContainer = ao_light_onPrimaryContainer,
    secondary = ao_light_secondary,
    onSecondary = ao_light_onSecondary,
    secondaryContainer = ao_light_secondaryContainer,
    onSecondaryContainer = ao_light_onSecondaryContainer,
    tertiary = ao_light_tertiary,
    onTertiary = ao_light_onTertiary,
    tertiaryContainer = ao_light_tertiaryContainer,
    onTertiaryContainer = ao_light_onTertiaryContainer,
    error = ao_light_error,
    errorContainer = ao_light_errorContainer,
    onError = ao_light_onError,
    onErrorContainer = ao_light_onErrorContainer,
    background = ao_light_background,
    onBackground = ao_light_onBackground,
    surface = ao_light_surface,
    onSurface = ao_light_onSurface,
    surfaceVariant = ao_light_surfaceVariant,
    onSurfaceVariant = ao_light_onSurfaceVariant,
    outline = ao_light_outline,
    inverseOnSurface = ao_light_inverseOnSurface,
    inverseSurface = ao_light_inverseSurface,
    inversePrimary = ao_light_inversePrimary,
    surfaceTint = ao_light_surfaceTint,
    outlineVariant = ao_light_outlineVariant,
    scrim = ao_light_scrim,
)

val aoDarkColors = darkColorScheme(
    primary = ao_dark_primary,
    onPrimary = ao_dark_onPrimary,
    primaryContainer = ao_dark_primaryContainer,
    onPrimaryContainer = ao_dark_onPrimaryContainer,
    secondary = ao_dark_secondary,
    onSecondary = ao_dark_onSecondary,
    secondaryContainer = ao_dark_secondaryContainer,
    onSecondaryContainer = ao_dark_onSecondaryContainer,
    tertiary = ao_dark_tertiary,
    onTertiary = ao_dark_onTertiary,
    tertiaryContainer = ao_dark_tertiaryContainer,
    onTertiaryContainer = ao_dark_onTertiaryContainer,
    error = ao_dark_error,
    errorContainer = ao_dark_errorContainer,
    onError = ao_dark_onError,
    onErrorContainer = ao_dark_onErrorContainer,
    background = ao_dark_background,
    onBackground = ao_dark_onBackground,
    surface = ao_dark_surface,
    onSurface = ao_dark_onSurface,
    surfaceVariant = ao_dark_surfaceVariant,
    onSurfaceVariant = ao_dark_onSurfaceVariant,
    outline = ao_dark_outline,
    inverseOnSurface = ao_dark_inverseOnSurface,
    inverseSurface = ao_dark_inverseSurface,
    inversePrimary = ao_dark_inversePrimary,
    surfaceTint = ao_dark_surfaceTint,
    outlineVariant = ao_dark_outlineVariant,
    scrim = ao_dark_scrim,
)
