package ir.thatsmejavad.backgroundable.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val aoLightPrimary = Color(0xFF006E00)
private val aoLightOnPrimary = Color(0xFFFFFFFF)
private val aoLightPrimaryContainer = Color(0xFF8DFB77)
private val aoLightOnPrimaryContainer = Color(0xFF002200)
private val aoLightSecondary = Color(0xFF54634D)
private val aoLightOnSecondary = Color(0xFFFFFFFF)
private val aoLightSecondaryContainer = Color(0xFFD7E8CD)
private val aoLightOnSecondaryContainer = Color(0xFF121F0E)
private val aoLightTertiary = Color(0xFF386568)
private val aoLightOnTertiary = Color(0xFFFFFFFF)
private val aoLightTertiaryContainer = Color(0xFFBCEBEE)
private val aoLightOnTertiaryContainer = Color(0xFF002022)
private val aoLightError = Color(0xFFBA1A1A)
private val aoLightErrorContainer = Color(0xFFFFDAD6)
private val aoLightOnError = Color(0xFFFFFFFF)
private val aoLightOnErrorContainer = Color(0xFF410002)
private val aoLightBackground = Color(0xFFFCFDF6)
private val aoLightOnBackground = Color(0xFF1A1C18)
private val aoLightSurface = Color(0xFFFCFDF6)
private val aoLightOnSurface = Color(0xFF1A1C18)
private val aoLightSurfaceVariant = Color(0xFFDFE4D7)
private val aoLightOnSurfaceVariant = Color(0xFF43483F)
private val aoLightOutline = Color(0xFF73796E)
private val aoLightInverseOnSurface = Color(0xFFF1F1EB)
private val aoLightInverseSurface = Color(0xFF2F312D)
private val aoLightInversePrimary = Color(0xFF72DE5E)
private val aoLightSurfaceTint = Color(0xFF006E00)
private val aoLightOutlineVariant = Color(0xFFC3C8BC)
private val aoLightScrim = Color(0xFF000000)

private val aoDarkPrimary = Color(0xFF72DE5E)
private val aoDarkOnPrimary = Color(0xFF003A00)
private val aoDarkPrimaryContainer = Color(0xFF005300)
private val aoDarkOnPrimaryContainer = Color(0xFF8DFB77)
private val aoDarkSecondary = Color(0xFFBBCBB2)
private val aoDarkOnSecondary = Color(0xFF263422)
private val aoDarkSecondaryContainer = Color(0xFF3C4B37)
private val aoDarkOnSecondaryContainer = Color(0xFFD7E8CD)
private val aoDarkTertiary = Color(0xFFA0CFD2)
private val aoDarkOnTertiary = Color(0xFF003739)
private val aoDarkTertiaryContainer = Color(0xFF1E4D50)
private val aoDarkOnTertiaryContainer = Color(0xFFBCEBEE)
private val aoDarkError = Color(0xFFFFB4AB)
private val aoDarkErrorContainer = Color(0xFF93000A)
private val aoDarkOnError = Color(0xFF690005)
private val aoDarkOnErrorContainer = Color(0xFFFFDAD6)
private val aoDarkBackground = Color(0xFF1A1C18)
private val aoDarkOnBackground = Color(0xFFE2E3DC)
private val aoDarkSurface = Color(0xFF1A1C18)
private val aoDarkOnSurface = Color(0xFFE2E3DC)
private val aoDarkSurfaceVariant = Color(0xFF43483F)
private val aoDarkOnSurfaceVariant = Color(0xFFC3C8BC)
private val aoDarkOutline = Color(0xFF8D9387)
private val aoDarkInverseOnSurface = Color(0xFF1A1C18)
private val aoDarkInverseSurface = Color(0xFFE2E3DC)
private val aoDarkInversePrimary = Color(0xFF006E00)
private val aoDarkSurfaceTint = Color(0xFF72DE5E)
private val aoDarkOutlineVariant = Color(0xFF43483F)
private val aoDarkScrim = Color(0xFF000000)

val aoLightColors = lightColorScheme(
    primary = aoLightPrimary,
    onPrimary = aoLightOnPrimary,
    primaryContainer = aoLightPrimaryContainer,
    onPrimaryContainer = aoLightOnPrimaryContainer,
    secondary = aoLightSecondary,
    onSecondary = aoLightOnSecondary,
    secondaryContainer = aoLightSecondaryContainer,
    onSecondaryContainer = aoLightOnSecondaryContainer,
    tertiary = aoLightTertiary,
    onTertiary = aoLightOnTertiary,
    tertiaryContainer = aoLightTertiaryContainer,
    onTertiaryContainer = aoLightOnTertiaryContainer,
    error = aoLightError,
    errorContainer = aoLightErrorContainer,
    onError = aoLightOnError,
    onErrorContainer = aoLightOnErrorContainer,
    background = aoLightBackground,
    onBackground = aoLightOnBackground,
    surface = aoLightSurface,
    onSurface = aoLightOnSurface,
    surfaceVariant = aoLightSurfaceVariant,
    onSurfaceVariant = aoLightOnSurfaceVariant,
    outline = aoLightOutline,
    inverseOnSurface = aoLightInverseOnSurface,
    inverseSurface = aoLightInverseSurface,
    inversePrimary = aoLightInversePrimary,
    surfaceTint = aoLightSurfaceTint,
    outlineVariant = aoLightOutlineVariant,
    scrim = aoLightScrim,
)

val aoDarkColors = darkColorScheme(
    primary = aoDarkPrimary,
    onPrimary = aoDarkOnPrimary,
    primaryContainer = aoDarkPrimaryContainer,
    onPrimaryContainer = aoDarkOnPrimaryContainer,
    secondary = aoDarkSecondary,
    onSecondary = aoDarkOnSecondary,
    secondaryContainer = aoDarkSecondaryContainer,
    onSecondaryContainer = aoDarkOnSecondaryContainer,
    tertiary = aoDarkTertiary,
    onTertiary = aoDarkOnTertiary,
    tertiaryContainer = aoDarkTertiaryContainer,
    onTertiaryContainer = aoDarkOnTertiaryContainer,
    error = aoDarkError,
    errorContainer = aoDarkErrorContainer,
    onError = aoDarkOnError,
    onErrorContainer = aoDarkOnErrorContainer,
    background = aoDarkBackground,
    onBackground = aoDarkOnBackground,
    surface = aoDarkSurface,
    onSurface = aoDarkOnSurface,
    surfaceVariant = aoDarkSurfaceVariant,
    onSurfaceVariant = aoDarkOnSurfaceVariant,
    outline = aoDarkOutline,
    inverseOnSurface = aoDarkInverseOnSurface,
    inverseSurface = aoDarkInverseSurface,
    inversePrimary = aoDarkInversePrimary,
    surfaceTint = aoDarkSurfaceTint,
    outlineVariant = aoDarkOutlineVariant,
    scrim = aoDarkScrim,
)
