package ir.thatsmejavad.backgroundable.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val blueVioletLightPrimary = Color(0xFF891BDC)
private val blueVioletLightOnPrimary = Color(0xFFFFFFFF)
private val blueVioletLightPrimaryContainer = Color(0xFFF1DAFF)
private val blueVioletLightOnPrimaryContainer = Color(0xFF2D004F)
private val blueVioletLightSecondary = Color(0xFF665A6F)
private val blueVioletLightOnSecondary = Color(0xFFFFFFFF)
private val blueVioletLightSecondaryContainer = Color(0xFFEDDDF6)
private val blueVioletLightOnSecondaryContainer = Color(0xFF211829)
private val blueVioletLightTertiary = Color(0xFF805156)
private val blueVioletLightOnTertiary = Color(0xFFFFFFFF)
private val blueVioletLightTertiaryContainer = Color(0xFFFFD9DC)
private val blueVioletLightOnTertiaryContainer = Color(0xFF321016)
private val blueVioletLightError = Color(0xFFBA1A1A)
private val blueVioletLightErrorContainer = Color(0xFFFFDAD6)
private val blueVioletLightOnError = Color(0xFFFFFFFF)
private val blueVioletLightOnErrorContainer = Color(0xFF410002)
private val blueVioletLightBackground = Color(0xFFFFFBFF)
private val blueVioletLightOnBackground = Color(0xFF1D1B1E)
private val blueVioletLightSurface = Color(0xFFFFFBFF)
private val blueVioletLightOnSurface = Color(0xFF1D1B1E)
private val blueVioletLightSurfaceVariant = Color(0xFFE9DFEA)
private val blueVioletLightOnSurfaceVariant = Color(0xFF4B454D)
private val blueVioletLightOutline = Color(0xFF7C757E)
private val blueVioletLightInverseOnSurface = Color(0xFFF6EFF3)
private val blueVioletLightInverseSurface = Color(0xFF322F33)
private val blueVioletLightInversePrimary = Color(0xFFDFB7FF)
private val blueVioletLightSurfaceTint = Color(0xFF891BDC)
private val blueVioletLightOutlineVariant = Color(0xFFCDC4CE)
private val blueVioletLightScrim = Color(0xFF000000)

private val blueVioletDarkPrimary = Color(0xFFDFB7FF)
private val blueVioletDarkOnPrimary = Color(0xFF4A007E)
private val blueVioletDarkPrimaryContainer = Color(0xFF6A00B1)
private val blueVioletDarkOnPrimaryContainer = Color(0xFFF1DAFF)
private val blueVioletDarkSecondary = Color(0xFFD1C1D9)
private val blueVioletDarkOnSecondary = Color(0xFF372C3F)
private val blueVioletDarkSecondaryContainer = Color(0xFF4E4256)
private val blueVioletDarkOnSecondaryContainer = Color(0xFFEDDDF6)
private val blueVioletDarkTertiary = Color(0xFFF3B7BC)
private val blueVioletDarkOnTertiary = Color(0xFF4C252A)
private val blueVioletDarkTertiaryContainer = Color(0xFF663A3F)
private val blueVioletDarkOnTertiaryContainer = Color(0xFFFFD9DC)
private val blueVioletDarkError = Color(0xFFFFB4AB)
private val blueVioletDarkErrorContainer = Color(0xFF93000A)
private val blueVioletDarkOnError = Color(0xFF690005)
private val blueVioletDarkOnErrorContainer = Color(0xFFFFDAD6)
private val blueVioletDarkBackground = Color(0xFF1D1B1E)
private val blueVioletDarkOnBackground = Color(0xFFE7E1E5)
private val blueVioletDarkSurface = Color(0xFF1D1B1E)
private val blueVioletDarkOnSurface = Color(0xFFE7E1E5)
private val blueVioletDarkSurfaceVariant = Color(0xFF4B454D)
private val blueVioletDarkOnSurfaceVariant = Color(0xFFCDC4CE)
private val blueVioletDarkOutline = Color(0xFF968E98)
private val blueVioletDarkInverseOnSurface = Color(0xFF1D1B1E)
private val blueVioletDarkInverseSurface = Color(0xFFE7E1E5)
private val blueVioletDarkInversePrimary = Color(0xFF891BDC)
private val blueVioletDarkSurfaceTint = Color(0xFFDFB7FF)
private val blueVioletDarkOutlineVariant = Color(0xFF4B454D)
private val blueVioletDarkScrim = Color(0xFF000000)

val blueVioletDarkColors = darkColorScheme(
    primary = blueVioletDarkPrimary,
    onPrimary = blueVioletDarkOnPrimary,
    primaryContainer = blueVioletDarkPrimaryContainer,
    onPrimaryContainer = blueVioletDarkOnPrimaryContainer,
    secondary = blueVioletDarkSecondary,
    onSecondary = blueVioletDarkOnSecondary,
    secondaryContainer = blueVioletDarkSecondaryContainer,
    onSecondaryContainer = blueVioletDarkOnSecondaryContainer,
    tertiary = blueVioletDarkTertiary,
    onTertiary = blueVioletDarkOnTertiary,
    tertiaryContainer = blueVioletDarkTertiaryContainer,
    onTertiaryContainer = blueVioletDarkOnTertiaryContainer,
    error = blueVioletDarkError,
    errorContainer = blueVioletDarkErrorContainer,
    onError = blueVioletDarkOnError,
    onErrorContainer = blueVioletDarkOnErrorContainer,
    background = blueVioletDarkBackground,
    onBackground = blueVioletDarkOnBackground,
    surface = blueVioletDarkSurface,
    onSurface = blueVioletDarkOnSurface,
    surfaceVariant = blueVioletDarkSurfaceVariant,
    onSurfaceVariant = blueVioletDarkOnSurfaceVariant,
    outline = blueVioletDarkOutline,
    inverseOnSurface = blueVioletDarkInverseOnSurface,
    inverseSurface = blueVioletDarkInverseSurface,
    inversePrimary = blueVioletDarkInversePrimary,
    surfaceTint = blueVioletDarkSurfaceTint,
    outlineVariant = blueVioletDarkOutlineVariant,
    scrim = blueVioletDarkScrim,
)

val blueVioletLightColors = lightColorScheme(
    primary = blueVioletLightPrimary,
    onPrimary = blueVioletLightOnPrimary,
    primaryContainer = blueVioletLightPrimaryContainer,
    onPrimaryContainer = blueVioletLightOnPrimaryContainer,
    secondary = blueVioletLightSecondary,
    onSecondary = blueVioletLightOnSecondary,
    secondaryContainer = blueVioletLightSecondaryContainer,
    onSecondaryContainer = blueVioletLightOnSecondaryContainer,
    tertiary = blueVioletLightTertiary,
    onTertiary = blueVioletLightOnTertiary,
    tertiaryContainer = blueVioletLightTertiaryContainer,
    onTertiaryContainer = blueVioletLightOnTertiaryContainer,
    error = blueVioletLightError,
    errorContainer = blueVioletLightErrorContainer,
    onError = blueVioletLightOnError,
    onErrorContainer = blueVioletLightOnErrorContainer,
    background = blueVioletLightBackground,
    onBackground = blueVioletLightOnBackground,
    surface = blueVioletLightSurface,
    onSurface = blueVioletLightOnSurface,
    surfaceVariant = blueVioletLightSurfaceVariant,
    onSurfaceVariant = blueVioletLightOnSurfaceVariant,
    outline = blueVioletLightOutline,
    inverseOnSurface = blueVioletLightInverseOnSurface,
    inverseSurface = blueVioletLightInverseSurface,
    inversePrimary = blueVioletLightInversePrimary,
    surfaceTint = blueVioletLightSurfaceTint,
    outlineVariant = blueVioletLightOutlineVariant,
    scrim = blueVioletLightScrim,
)
