package ir.thatsmejavad.backgroundable.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val blue_violet_light_primary = Color(0xFF891BDC)
private val blue_violet_light_onPrimary = Color(0xFFFFFFFF)
private val blue_violet_light_primaryContainer = Color(0xFFF1DAFF)
private val blue_violet_light_onPrimaryContainer = Color(0xFF2D004F)
private val blue_violet_light_secondary = Color(0xFF665A6F)
private val blue_violet_light_onSecondary = Color(0xFFFFFFFF)
private val blue_violet_light_secondaryContainer = Color(0xFFEDDDF6)
private val blue_violet_light_onSecondaryContainer = Color(0xFF211829)
private val blue_violet_light_tertiary = Color(0xFF805156)
private val blue_violet_light_onTertiary = Color(0xFFFFFFFF)
private val blue_violet_light_tertiaryContainer = Color(0xFFFFD9DC)
private val blue_violet_light_onTertiaryContainer = Color(0xFF321016)
private val blue_violet_light_error = Color(0xFFBA1A1A)
private val blue_violet_light_errorContainer = Color(0xFFFFDAD6)
private val blue_violet_light_onError = Color(0xFFFFFFFF)
private val blue_violet_light_onErrorContainer = Color(0xFF410002)
private val blue_violet_light_background = Color(0xFFFFFBFF)
private val blue_violet_light_onBackground = Color(0xFF1D1B1E)
private val blue_violet_light_surface = Color(0xFFFFFBFF)
private val blue_violet_light_onSurface = Color(0xFF1D1B1E)
private val blue_violet_light_surfaceVariant = Color(0xFFE9DFEA)
private val blue_violet_light_onSurfaceVariant = Color(0xFF4B454D)
private val blue_violet_light_outline = Color(0xFF7C757E)
private val blue_violet_light_inverseOnSurface = Color(0xFFF6EFF3)
private val blue_violet_light_inverseSurface = Color(0xFF322F33)
private val blue_violet_light_inversePrimary = Color(0xFFDFB7FF)
private val blue_violet_light_surfaceTint = Color(0xFF891BDC)
private val blue_violet_light_outlineVariant = Color(0xFFCDC4CE)
private val blue_violet_light_scrim = Color(0xFF000000)

private val blue_violet_dark_primary = Color(0xFFDFB7FF)
private val blue_violet_dark_onPrimary = Color(0xFF4A007E)
private val blue_violet_dark_primaryContainer = Color(0xFF6A00B1)
private val blue_violet_dark_onPrimaryContainer = Color(0xFFF1DAFF)
private val blue_violet_dark_secondary = Color(0xFFD1C1D9)
private val blue_violet_dark_onSecondary = Color(0xFF372C3F)
private val blue_violet_dark_secondaryContainer = Color(0xFF4E4256)
private val blue_violet_dark_onSecondaryContainer = Color(0xFFEDDDF6)
private val blue_violet_dark_tertiary = Color(0xFFF3B7BC)
private val blue_violet_dark_onTertiary = Color(0xFF4C252A)
private val blue_violet_dark_tertiaryContainer = Color(0xFF663A3F)
private val blue_violet_dark_onTertiaryContainer = Color(0xFFFFD9DC)
private val blue_violet_dark_error = Color(0xFFFFB4AB)
private val blue_violet_dark_errorContainer = Color(0xFF93000A)
private val blue_violet_dark_onError = Color(0xFF690005)
private val blue_violet_dark_onErrorContainer = Color(0xFFFFDAD6)
private val blue_violet_dark_background = Color(0xFF1D1B1E)
private val blue_violet_dark_onBackground = Color(0xFFE7E1E5)
private val blue_violet_dark_surface = Color(0xFF1D1B1E)
private val blue_violet_dark_onSurface = Color(0xFFE7E1E5)
private val blue_violet_dark_surfaceVariant = Color(0xFF4B454D)
private val blue_violet_dark_onSurfaceVariant = Color(0xFFCDC4CE)
private val blue_violet_dark_outline = Color(0xFF968E98)
private val blue_violet_dark_inverseOnSurface = Color(0xFF1D1B1E)
private val blue_violet_dark_inverseSurface = Color(0xFFE7E1E5)
private val blue_violet_dark_inversePrimary = Color(0xFF891BDC)
private val blue_violet_dark_surfaceTint = Color(0xFFDFB7FF)
private val blue_violet_dark_outlineVariant = Color(0xFF4B454D)
private val blue_violet_dark_scrim = Color(0xFF000000)

val blueVioletDarkColors = darkColorScheme(
    primary = blue_violet_dark_primary,
    onPrimary = blue_violet_dark_onPrimary,
    primaryContainer = blue_violet_dark_primaryContainer,
    onPrimaryContainer = blue_violet_dark_onPrimaryContainer,
    secondary = blue_violet_dark_secondary,
    onSecondary = blue_violet_dark_onSecondary,
    secondaryContainer = blue_violet_dark_secondaryContainer,
    onSecondaryContainer = blue_violet_dark_onSecondaryContainer,
    tertiary = blue_violet_dark_tertiary,
    onTertiary = blue_violet_dark_onTertiary,
    tertiaryContainer = blue_violet_dark_tertiaryContainer,
    onTertiaryContainer = blue_violet_dark_onTertiaryContainer,
    error = blue_violet_dark_error,
    errorContainer = blue_violet_dark_errorContainer,
    onError = blue_violet_dark_onError,
    onErrorContainer = blue_violet_dark_onErrorContainer,
    background = blue_violet_dark_background,
    onBackground = blue_violet_dark_onBackground,
    surface = blue_violet_dark_surface,
    onSurface = blue_violet_dark_onSurface,
    surfaceVariant = blue_violet_dark_surfaceVariant,
    onSurfaceVariant = blue_violet_dark_onSurfaceVariant,
    outline = blue_violet_dark_outline,
    inverseOnSurface = blue_violet_dark_inverseOnSurface,
    inverseSurface = blue_violet_dark_inverseSurface,
    inversePrimary = blue_violet_dark_inversePrimary,
    surfaceTint = blue_violet_dark_surfaceTint,
    outlineVariant = blue_violet_dark_outlineVariant,
    scrim = blue_violet_dark_scrim,
)

val blueVioletLightColors = lightColorScheme(
    primary = blue_violet_light_primary,
    onPrimary = blue_violet_light_onPrimary,
    primaryContainer = blue_violet_light_primaryContainer,
    onPrimaryContainer = blue_violet_light_onPrimaryContainer,
    secondary = blue_violet_light_secondary,
    onSecondary = blue_violet_light_onSecondary,
    secondaryContainer = blue_violet_light_secondaryContainer,
    onSecondaryContainer = blue_violet_light_onSecondaryContainer,
    tertiary = blue_violet_light_tertiary,
    onTertiary = blue_violet_light_onTertiary,
    tertiaryContainer = blue_violet_light_tertiaryContainer,
    onTertiaryContainer = blue_violet_light_onTertiaryContainer,
    error = blue_violet_light_error,
    errorContainer = blue_violet_light_errorContainer,
    onError = blue_violet_light_onError,
    onErrorContainer = blue_violet_light_onErrorContainer,
    background = blue_violet_light_background,
    onBackground = blue_violet_light_onBackground,
    surface = blue_violet_light_surface,
    onSurface = blue_violet_light_onSurface,
    surfaceVariant = blue_violet_light_surfaceVariant,
    onSurfaceVariant = blue_violet_light_onSurfaceVariant,
    outline = blue_violet_light_outline,
    inverseOnSurface = blue_violet_light_inverseOnSurface,
    inverseSurface = blue_violet_light_inverseSurface,
    inversePrimary = blue_violet_light_inversePrimary,
    surfaceTint = blue_violet_light_surfaceTint,
    outlineVariant = blue_violet_light_outlineVariant,
    scrim = blue_violet_light_scrim,
)
