package ir.thatsmejavad.backgroundable.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val crayola_light_primary = Color(0xFFBD0041)
private val crayola_light_onPrimary = Color(0xFFFFFFFF)
private val crayola_light_primaryContainer = Color(0xFFFFD9DC)
private val crayola_light_onPrimaryContainer = Color(0xFF400010)
private val crayola_light_secondary = Color(0xFF765659)
private val crayola_light_onSecondary = Color(0xFFFFFFFF)
private val crayola_light_secondaryContainer = Color(0xFFFFD9DC)
private val crayola_light_onSecondaryContainer = Color(0xFF2C1518)
private val crayola_light_tertiary = Color(0xFF785930)
private val crayola_light_onTertiary = Color(0xFFFFFFFF)
private val crayola_light_tertiaryContainer = Color(0xFFFFDDB6)
private val crayola_light_onTertiaryContainer = Color(0xFF2A1800)
private val crayola_light_error = Color(0xFFBA1A1A)
private val crayola_light_errorContainer = Color(0xFFFFDAD6)
private val crayola_light_onError = Color(0xFFFFFFFF)
private val crayola_light_onErrorContainer = Color(0xFF410002)
private val crayola_light_background = Color(0xFFFFFBFF)
private val crayola_light_onBackground = Color(0xFF201A1A)
private val crayola_light_surface = Color(0xFFFFFBFF)
private val crayola_light_onSurface = Color(0xFF201A1A)
private val crayola_light_surfaceVariant = Color(0xFFF4DDDE)
private val crayola_light_onSurfaceVariant = Color(0xFF524344)
private val crayola_light_outline = Color(0xFF847374)
private val crayola_light_inverseOnSurface = Color(0xFFFBEEEE)
private val crayola_light_inverseSurface = Color(0xFF362F2F)
private val crayola_light_inversePrimary = Color(0xFFFFB2BA)
private val crayola_light_surfaceTint = Color(0xFFBD0041)
private val crayola_light_outlineVariant = Color(0xFFD7C1C2)
private val crayola_light_scrim = Color(0xFF000000)

private val crayola_dark_primary = Color(0xFFFFB2BA)
private val crayola_dark_onPrimary = Color(0xFF670020)
private val crayola_dark_primaryContainer = Color(0xFF910030)
private val crayola_dark_onPrimaryContainer = Color(0xFFFFD9DC)
private val crayola_dark_secondary = Color(0xFFE5BDC0)
private val crayola_dark_onSecondary = Color(0xFF43292C)
private val crayola_dark_secondaryContainer = Color(0xFF5C3F42)
private val crayola_dark_onSecondaryContainer = Color(0xFFFFD9DC)
private val crayola_dark_tertiary = Color(0xFFE9BF8E)
private val crayola_dark_onTertiary = Color(0xFF442B07)
private val crayola_dark_tertiaryContainer = Color(0xFF5D411B)
private val crayola_dark_onTertiaryContainer = Color(0xFFFFDDB6)
private val crayola_dark_error = Color(0xFFFFB4AB)
private val crayola_dark_errorContainer = Color(0xFF93000A)
private val crayola_dark_onError = Color(0xFF690005)
private val crayola_dark_onErrorContainer = Color(0xFFFFDAD6)
private val crayola_dark_background = Color(0xFF201A1A)
private val crayola_dark_onBackground = Color(0xFFECE0E0)
private val crayola_dark_surface = Color(0xFF201A1A)
private val crayola_dark_onSurface = Color(0xFFECE0E0)
private val crayola_dark_surfaceVariant = Color(0xFF524344)
private val crayola_dark_onSurfaceVariant = Color(0xFFD7C1C2)
private val crayola_dark_outline = Color(0xFF9F8C8D)
private val crayola_dark_inverseOnSurface = Color(0xFF201A1A)
private val crayola_dark_inverseSurface = Color(0xFFECE0E0)
private val crayola_dark_inversePrimary = Color(0xFFBD0041)
private val crayola_dark_surfaceTint = Color(0xFFFFB2BA)
private val crayola_dark_outlineVariant = Color(0xFF524344)
private val crayola_dark_scrim = Color(0xFF000000)

val crayolaLightColors = lightColorScheme(
    primary = crayola_light_primary,
    onPrimary = crayola_light_onPrimary,
    primaryContainer = crayola_light_primaryContainer,
    onPrimaryContainer = crayola_light_onPrimaryContainer,
    secondary = crayola_light_secondary,
    onSecondary = crayola_light_onSecondary,
    secondaryContainer = crayola_light_secondaryContainer,
    onSecondaryContainer = crayola_light_onSecondaryContainer,
    tertiary = crayola_light_tertiary,
    onTertiary = crayola_light_onTertiary,
    tertiaryContainer = crayola_light_tertiaryContainer,
    onTertiaryContainer = crayola_light_onTertiaryContainer,
    error = crayola_light_error,
    errorContainer = crayola_light_errorContainer,
    onError = crayola_light_onError,
    onErrorContainer = crayola_light_onErrorContainer,
    background = crayola_light_background,
    onBackground = crayola_light_onBackground,
    surface = crayola_light_surface,
    onSurface = crayola_light_onSurface,
    surfaceVariant = crayola_light_surfaceVariant,
    onSurfaceVariant = crayola_light_onSurfaceVariant,
    outline = crayola_light_outline,
    inverseOnSurface = crayola_light_inverseOnSurface,
    inverseSurface = crayola_light_inverseSurface,
    inversePrimary = crayola_light_inversePrimary,
    surfaceTint = crayola_light_surfaceTint,
    outlineVariant = crayola_light_outlineVariant,
    scrim = crayola_light_scrim,
)

val crayolaDarkColors = darkColorScheme(
    primary = crayola_dark_primary,
    onPrimary = crayola_dark_onPrimary,
    primaryContainer = crayola_dark_primaryContainer,
    onPrimaryContainer = crayola_dark_onPrimaryContainer,
    secondary = crayola_dark_secondary,
    onSecondary = crayola_dark_onSecondary,
    secondaryContainer = crayola_dark_secondaryContainer,
    onSecondaryContainer = crayola_dark_onSecondaryContainer,
    tertiary = crayola_dark_tertiary,
    onTertiary = crayola_dark_onTertiary,
    tertiaryContainer = crayola_dark_tertiaryContainer,
    onTertiaryContainer = crayola_dark_onTertiaryContainer,
    error = crayola_dark_error,
    errorContainer = crayola_dark_errorContainer,
    onError = crayola_dark_onError,
    onErrorContainer = crayola_dark_onErrorContainer,
    background = crayola_dark_background,
    onBackground = crayola_dark_onBackground,
    surface = crayola_dark_surface,
    onSurface = crayola_dark_onSurface,
    surfaceVariant = crayola_dark_surfaceVariant,
    onSurfaceVariant = crayola_dark_onSurfaceVariant,
    outline = crayola_dark_outline,
    inverseOnSurface = crayola_dark_inverseOnSurface,
    inverseSurface = crayola_dark_inverseSurface,
    inversePrimary = crayola_dark_inversePrimary,
    surfaceTint = crayola_dark_surfaceTint,
    outlineVariant = crayola_dark_outlineVariant,
    scrim = crayola_dark_scrim,
)
