package ir.thatsmejavad.backgroundable.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val crayolaLightPrimary = Color(0xFFBD0041)
private val crayolaLightOnPrimary = Color(0xFFFFFFFF)
private val crayolaLightPrimaryContainer = Color(0xFFFFD9DC)
private val crayolaLightOnPrimaryContainer = Color(0xFF400010)
private val crayolaLightSecondary = Color(0xFF765659)
private val crayolaLightOnSecondary = Color(0xFFFFFFFF)
private val crayolaLightSecondaryContainer = Color(0xFFFFD9DC)
private val crayolaLightOnSecondaryContainer = Color(0xFF2C1518)
private val crayolaLightTertiary = Color(0xFF785930)
private val crayolaLightOnTertiary = Color(0xFFFFFFFF)
private val crayolaLightTertiaryContainer = Color(0xFFFFDDB6)
private val crayolaLightOnTertiaryContainer = Color(0xFF2A1800)
private val crayolaLightError = Color(0xFFBA1A1A)
private val crayolaLightErrorContainer = Color(0xFFFFDAD6)
private val crayolaLightOnError = Color(0xFFFFFFFF)
private val crayolaLightOnErrorContainer = Color(0xFF410002)
private val crayolaLightBackground = Color(0xFFFFFBFF)
private val crayolaLightOnBackground = Color(0xFF201A1A)
private val crayolaLightSurface = Color(0xFFFFFBFF)
private val crayolaLightOnSurface = Color(0xFF201A1A)
private val crayolaLightSurfaceVariant = Color(0xFFF4DDDE)
private val crayolaLightOnSurfaceVariant = Color(0xFF524344)
private val crayolaLightOutline = Color(0xFF847374)
private val crayolaLightInverseOnSurface = Color(0xFFFBEEEE)
private val crayolaLightInverseSurface = Color(0xFF362F2F)
private val crayolaLightInversePrimary = Color(0xFFFFB2BA)
private val crayolaLightSurfaceTint = Color(0xFFBD0041)
private val crayolaLightOutlineVariant = Color(0xFFD7C1C2)
private val crayolaLightScrim = Color(0xFF000000)

private val crayolaDarkPrimary = Color(0xFFFFB2BA)
private val crayolaDarkOnPrimary = Color(0xFF670020)
private val crayolaDarkPrimaryContainer = Color(0xFF910030)
private val crayolaDarkOnPrimaryContainer = Color(0xFFFFD9DC)
private val crayolaDarkSecondary = Color(0xFFE5BDC0)
private val crayolaDarkOnSecondary = Color(0xFF43292C)
private val crayolaDarkSecondaryContainer = Color(0xFF5C3F42)
private val crayolaDarkOnSecondaryContainer = Color(0xFFFFD9DC)
private val crayolaDarkTertiary = Color(0xFFE9BF8E)
private val crayolaDarkOnTertiary = Color(0xFF442B07)
private val crayolaDarkTertiaryContainer = Color(0xFF5D411B)
private val crayolaDarkOnTertiaryContainer = Color(0xFFFFDDB6)
private val crayolaDarkError = Color(0xFFFFB4AB)
private val crayolaDarkErrorContainer = Color(0xFF93000A)
private val crayolaDarkOnError = Color(0xFF690005)
private val crayolaDarkOnErrorContainer = Color(0xFFFFDAD6)
private val crayolaDarkBackground = Color(0xFF201A1A)
private val crayolaDarkOnBackground = Color(0xFFECE0E0)
private val crayolaDarkSurface = Color(0xFF201A1A)
private val crayolaDarkOnSurface = Color(0xFFECE0E0)
private val crayolaDarkSurfaceVariant = Color(0xFF524344)
private val crayolaDarkOnSurfaceVariant = Color(0xFFD7C1C2)
private val crayolaDarkOutline = Color(0xFF9F8C8D)
private val crayolaDarkInverseOnSurface = Color(0xFF201A1A)
private val crayolaDarkInverseSurface = Color(0xFFECE0E0)
private val crayolaDarkInversePrimary = Color(0xFFBD0041)
private val crayolaDarkSurfaceTint = Color(0xFFFFB2BA)
private val crayolaDarkOutlineVariant = Color(0xFF524344)
private val crayolaDarkScrim = Color(0xFF000000)

val crayolaLightColors = lightColorScheme(
    primary = crayolaLightPrimary,
    onPrimary = crayolaLightOnPrimary,
    primaryContainer = crayolaLightPrimaryContainer,
    onPrimaryContainer = crayolaLightOnPrimaryContainer,
    secondary = crayolaLightSecondary,
    onSecondary = crayolaLightOnSecondary,
    secondaryContainer = crayolaLightSecondaryContainer,
    onSecondaryContainer = crayolaLightOnSecondaryContainer,
    tertiary = crayolaLightTertiary,
    onTertiary = crayolaLightOnTertiary,
    tertiaryContainer = crayolaLightTertiaryContainer,
    onTertiaryContainer = crayolaLightOnTertiaryContainer,
    error = crayolaLightError,
    errorContainer = crayolaLightErrorContainer,
    onError = crayolaLightOnError,
    onErrorContainer = crayolaLightOnErrorContainer,
    background = crayolaLightBackground,
    onBackground = crayolaLightOnBackground,
    surface = crayolaLightSurface,
    onSurface = crayolaLightOnSurface,
    surfaceVariant = crayolaLightSurfaceVariant,
    onSurfaceVariant = crayolaLightOnSurfaceVariant,
    outline = crayolaLightOutline,
    inverseOnSurface = crayolaLightInverseOnSurface,
    inverseSurface = crayolaLightInverseSurface,
    inversePrimary = crayolaLightInversePrimary,
    surfaceTint = crayolaLightSurfaceTint,
    outlineVariant = crayolaLightOutlineVariant,
    scrim = crayolaLightScrim,
)

val crayolaDarkColors = darkColorScheme(
    primary = crayolaDarkPrimary,
    onPrimary = crayolaDarkOnPrimary,
    primaryContainer = crayolaDarkPrimaryContainer,
    onPrimaryContainer = crayolaDarkOnPrimaryContainer,
    secondary = crayolaDarkSecondary,
    onSecondary = crayolaDarkOnSecondary,
    secondaryContainer = crayolaDarkSecondaryContainer,
    onSecondaryContainer = crayolaDarkOnSecondaryContainer,
    tertiary = crayolaDarkTertiary,
    onTertiary = crayolaDarkOnTertiary,
    tertiaryContainer = crayolaDarkTertiaryContainer,
    onTertiaryContainer = crayolaDarkOnTertiaryContainer,
    error = crayolaDarkError,
    errorContainer = crayolaDarkErrorContainer,
    onError = crayolaDarkOnError,
    onErrorContainer = crayolaDarkOnErrorContainer,
    background = crayolaDarkBackground,
    onBackground = crayolaDarkOnBackground,
    surface = crayolaDarkSurface,
    onSurface = crayolaDarkOnSurface,
    surfaceVariant = crayolaDarkSurfaceVariant,
    onSurfaceVariant = crayolaDarkOnSurfaceVariant,
    outline = crayolaDarkOutline,
    inverseOnSurface = crayolaDarkInverseOnSurface,
    inverseSurface = crayolaDarkInverseSurface,
    inversePrimary = crayolaDarkInversePrimary,
    surfaceTint = crayolaDarkSurfaceTint,
    outlineVariant = crayolaDarkOutlineVariant,
    scrim = crayolaDarkScrim,
)
