package ir.thatsmejavad.backgroundable.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val indigo_light_primary = Color(0xFF1960A5)
private val indigo_light_onPrimary = Color(0xFFFFFFFF)
private val indigo_light_primaryContainer = Color(0xFFD3E3FF)
private val indigo_light_onPrimaryContainer = Color(0xFF001C39)
private val indigo_light_secondary = Color(0xFF545F71)
private val indigo_light_onSecondary = Color(0xFFFFFFFF)
private val indigo_light_secondaryContainer = Color(0xFFD8E3F8)
private val indigo_light_onSecondaryContainer = Color(0xFF111C2B)
private val indigo_light_tertiary = Color(0xFF6D5677)
private val indigo_light_onTertiary = Color(0xFFFFFFFF)
private val indigo_light_tertiaryContainer = Color(0xFFF6D9FF)
private val indigo_light_onTertiaryContainer = Color(0xFF261430)
private val indigo_light_error = Color(0xFFBA1A1A)
private val indigo_light_errorContainer = Color(0xFFFFDAD6)
private val indigo_light_onError = Color(0xFFFFFFFF)
private val indigo_light_onErrorContainer = Color(0xFF410002)
private val indigo_light_background = Color(0xFFFDFCFF)
private val indigo_light_onBackground = Color(0xFF1A1C1E)
private val indigo_light_surface = Color(0xFFFDFCFF)
private val indigo_light_onSurface = Color(0xFF1A1C1E)
private val indigo_light_surfaceVariant = Color(0xFFDFE2EB)
private val indigo_light_onSurfaceVariant = Color(0xFF43474E)
private val indigo_light_outline = Color(0xFF73777F)
private val indigo_light_inverseOnSurface = Color(0xFFF1F0F4)
private val indigo_light_inverseSurface = Color(0xFF2F3033)
private val indigo_light_inversePrimary = Color(0xFFA3C9FF)
private val indigo_light_surfaceTint = Color(0xFF1960A5)
private val indigo_light_outlineVariant = Color(0xFFC3C6CF)
private val indigo_light_scrim = Color(0xFF000000)

private val indigo_dark_primary = Color(0xFFA3C9FF)
private val indigo_dark_onPrimary = Color(0xFF00315D)
private val indigo_dark_primaryContainer = Color(0xFF004883)
private val indigo_dark_onPrimaryContainer = Color(0xFFD3E3FF)
private val indigo_dark_secondary = Color(0xFFBCC7DB)
private val indigo_dark_onSecondary = Color(0xFF263141)
private val indigo_dark_secondaryContainer = Color(0xFF3C4758)
private val indigo_dark_onSecondaryContainer = Color(0xFFD8E3F8)
private val indigo_dark_tertiary = Color(0xFFD9BDE3)
private val indigo_dark_onTertiary = Color(0xFF3D2946)
private val indigo_dark_tertiaryContainer = Color(0xFF543F5E)
private val indigo_dark_onTertiaryContainer = Color(0xFFF6D9FF)
private val indigo_dark_error = Color(0xFFFFB4AB)
private val indigo_dark_errorContainer = Color(0xFF93000A)
private val indigo_dark_onError = Color(0xFF690005)
private val indigo_dark_onErrorContainer = Color(0xFFFFDAD6)
private val indigo_dark_background = Color(0xFF1A1C1E)
private val indigo_dark_onBackground = Color(0xFFE3E2E6)
private val indigo_dark_surface = Color(0xFF1A1C1E)
private val indigo_dark_onSurface = Color(0xFFE3E2E6)
private val indigo_dark_surfaceVariant = Color(0xFF43474E)
private val indigo_dark_onSurfaceVariant = Color(0xFFC3C6CF)
private val indigo_dark_outline = Color(0xFF8D9199)
private val indigo_dark_inverseOnSurface = Color(0xFF1A1C1E)
private val indigo_dark_inverseSurface = Color(0xFFE3E2E6)
private val indigo_dark_inversePrimary = Color(0xFF1960A5)
private val indigo_dark_surfaceTint = Color(0xFFA3C9FF)
private val indigo_dark_outlineVariant = Color(0xFF43474E)
private val indigo_dark_scrim = Color(0xFF000000)

val indigoLightColors = lightColorScheme(
    primary = indigo_light_primary,
    onPrimary = indigo_light_onPrimary,
    primaryContainer = indigo_light_primaryContainer,
    onPrimaryContainer = indigo_light_onPrimaryContainer,
    secondary = indigo_light_secondary,
    onSecondary = indigo_light_onSecondary,
    secondaryContainer = indigo_light_secondaryContainer,
    onSecondaryContainer = indigo_light_onSecondaryContainer,
    tertiary = indigo_light_tertiary,
    onTertiary = indigo_light_onTertiary,
    tertiaryContainer = indigo_light_tertiaryContainer,
    onTertiaryContainer = indigo_light_onTertiaryContainer,
    error = indigo_light_error,
    errorContainer = indigo_light_errorContainer,
    onError = indigo_light_onError,
    onErrorContainer = indigo_light_onErrorContainer,
    background = indigo_light_background,
    onBackground = indigo_light_onBackground,
    surface = indigo_light_surface,
    onSurface = indigo_light_onSurface,
    surfaceVariant = indigo_light_surfaceVariant,
    onSurfaceVariant = indigo_light_onSurfaceVariant,
    outline = indigo_light_outline,
    inverseOnSurface = indigo_light_inverseOnSurface,
    inverseSurface = indigo_light_inverseSurface,
    inversePrimary = indigo_light_inversePrimary,
    surfaceTint = indigo_light_surfaceTint,
    outlineVariant = indigo_light_outlineVariant,
    scrim = indigo_light_scrim,
)

val indigoDarkColors = darkColorScheme(
    primary = indigo_dark_primary,
    onPrimary = indigo_dark_onPrimary,
    primaryContainer = indigo_dark_primaryContainer,
    onPrimaryContainer = indigo_dark_onPrimaryContainer,
    secondary = indigo_dark_secondary,
    onSecondary = indigo_dark_onSecondary,
    secondaryContainer = indigo_dark_secondaryContainer,
    onSecondaryContainer = indigo_dark_onSecondaryContainer,
    tertiary = indigo_dark_tertiary,
    onTertiary = indigo_dark_onTertiary,
    tertiaryContainer = indigo_dark_tertiaryContainer,
    onTertiaryContainer = indigo_dark_onTertiaryContainer,
    error = indigo_dark_error,
    errorContainer = indigo_dark_errorContainer,
    onError = indigo_dark_onError,
    onErrorContainer = indigo_dark_onErrorContainer,
    background = indigo_dark_background,
    onBackground = indigo_dark_onBackground,
    surface = indigo_dark_surface,
    onSurface = indigo_dark_onSurface,
    surfaceVariant = indigo_dark_surfaceVariant,
    onSurfaceVariant = indigo_dark_onSurfaceVariant,
    outline = indigo_dark_outline,
    inverseOnSurface = indigo_dark_inverseOnSurface,
    inverseSurface = indigo_dark_inverseSurface,
    inversePrimary = indigo_dark_inversePrimary,
    surfaceTint = indigo_dark_surfaceTint,
    outlineVariant = indigo_dark_outlineVariant,
    scrim = indigo_dark_scrim,
)
