package ir.thatsmejavad.backgroundable.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val indigoLightPrimary = Color(0xFF1960A5)
private val indigoLightOnPrimary = Color(0xFFFFFFFF)
private val indigoLightPrimaryContainer = Color(0xFFD3E3FF)
private val indigoLightOnPrimaryContainer = Color(0xFF001C39)
private val indigoLightSecondary = Color(0xFF545F71)
private val indigoLightOnSecondary = Color(0xFFFFFFFF)
private val indigoLightSecondaryContainer = Color(0xFFD8E3F8)
private val indigoLightOnSecondaryContainer = Color(0xFF111C2B)
private val indigoLightTertiary = Color(0xFF6D5677)
private val indigoLightOnTertiary = Color(0xFFFFFFFF)
private val indigoLightTertiaryContainer = Color(0xFFF6D9FF)
private val indigoLightOnTertiaryContainer = Color(0xFF261430)
private val indigoLightError = Color(0xFFBA1A1A)
private val indigoLightErrorContainer = Color(0xFFFFDAD6)
private val indigoLightOnError = Color(0xFFFFFFFF)
private val indigoLightOnErrorContainer = Color(0xFF410002)
private val indigoLightBackground = Color(0xFFFDFCFF)
private val indigoLightOnBackground = Color(0xFF1A1C1E)
private val indigoLightSurface = Color(0xFFFDFCFF)
private val indigoLightOnSurface = Color(0xFF1A1C1E)
private val indigoLightSurfaceVariant = Color(0xFFDFE2EB)
private val indigoLightOnSurfaceVariant = Color(0xFF43474E)
private val indigoLightOutline = Color(0xFF73777F)
private val indigoLightInverseOnSurface = Color(0xFFF1F0F4)
private val indigoLightInverseSurface = Color(0xFF2F3033)
private val indigoLightInversePrimary = Color(0xFFA3C9FF)
private val indigoLightSurfaceTint = Color(0xFF1960A5)
private val indigoLightOutlineVariant = Color(0xFFC3C6CF)
private val indigoLightScrim = Color(0xFF000000)

private val indigoDarkPrimary = Color(0xFFA3C9FF)
private val indigoDarkOnPrimary = Color(0xFF00315D)
private val indigoDarkPrimaryContainer = Color(0xFF004883)
private val indigoDarkOnPrimaryContainer = Color(0xFFD3E3FF)
private val indigoDarkSecondary = Color(0xFFBCC7DB)
private val indigoDarkOnSecondary = Color(0xFF263141)
private val indigoDarkSecondaryContainer = Color(0xFF3C4758)
private val indigoDarkOnSecondaryContainer = Color(0xFFD8E3F8)
private val indigoDarkTertiary = Color(0xFFD9BDE3)
private val indigoDarkOnTertiary = Color(0xFF3D2946)
private val indigoDarkTertiaryContainer = Color(0xFF543F5E)
private val indigoDarkOnTertiaryContainer = Color(0xFFF6D9FF)
private val indigoDarkError = Color(0xFFFFB4AB)
private val indigoDarkErrorContainer = Color(0xFF93000A)
private val indigoDarkOnError = Color(0xFF690005)
private val indigoDarkOnErrorContainer = Color(0xFFFFDAD6)
private val indigoDarkBackground = Color(0xFF1A1C1E)
private val indigoDarkOnBackground = Color(0xFFE3E2E6)
private val indigoDarkSurface = Color(0xFF1A1C1E)
private val indigoDarkOnSurface = Color(0xFFE3E2E6)
private val indigoDarkSurfaceVariant = Color(0xFF43474E)
private val indigoDarkOnSurfaceVariant = Color(0xFFC3C6CF)
private val indigoDarkOutline = Color(0xFF8D9199)
private val indigoDarkInverseOnSurface = Color(0xFF1A1C1E)
private val indigoDarkInverseSurface = Color(0xFFE3E2E6)
private val indigoDarkInversePrimary = Color(0xFF1960A5)
private val indigoDarkSurfaceTint = Color(0xFFA3C9FF)
private val indigoDarkOutlineVariant = Color(0xFF43474E)
private val indigoDarkScrim = Color(0xFF000000)

val indigoLightColors = lightColorScheme(
    primary = indigoLightPrimary,
    onPrimary = indigoLightOnPrimary,
    primaryContainer = indigoLightPrimaryContainer,
    onPrimaryContainer = indigoLightOnPrimaryContainer,
    secondary = indigoLightSecondary,
    onSecondary = indigoLightOnSecondary,
    secondaryContainer = indigoLightSecondaryContainer,
    onSecondaryContainer = indigoLightOnSecondaryContainer,
    tertiary = indigoLightTertiary,
    onTertiary = indigoLightOnTertiary,
    tertiaryContainer = indigoLightTertiaryContainer,
    onTertiaryContainer = indigoLightOnTertiaryContainer,
    error = indigoLightError,
    errorContainer = indigoLightErrorContainer,
    onError = indigoLightOnError,
    onErrorContainer = indigoLightOnErrorContainer,
    background = indigoLightBackground,
    onBackground = indigoLightOnBackground,
    surface = indigoLightSurface,
    onSurface = indigoLightOnSurface,
    surfaceVariant = indigoLightSurfaceVariant,
    onSurfaceVariant = indigoLightOnSurfaceVariant,
    outline = indigoLightOutline,
    inverseOnSurface = indigoLightInverseOnSurface,
    inverseSurface = indigoLightInverseSurface,
    inversePrimary = indigoLightInversePrimary,
    surfaceTint = indigoLightSurfaceTint,
    outlineVariant = indigoLightOutlineVariant,
    scrim = indigoLightScrim,
)

val indigoDarkColors = darkColorScheme(
    primary = indigoDarkPrimary,
    onPrimary = indigoDarkOnPrimary,
    primaryContainer = indigoDarkPrimaryContainer,
    onPrimaryContainer = indigoDarkOnPrimaryContainer,
    secondary = indigoDarkSecondary,
    onSecondary = indigoDarkOnSecondary,
    secondaryContainer = indigoDarkSecondaryContainer,
    onSecondaryContainer = indigoDarkOnSecondaryContainer,
    tertiary = indigoDarkTertiary,
    onTertiary = indigoDarkOnTertiary,
    tertiaryContainer = indigoDarkTertiaryContainer,
    onTertiaryContainer = indigoDarkOnTertiaryContainer,
    error = indigoDarkError,
    errorContainer = indigoDarkErrorContainer,
    onError = indigoDarkOnError,
    onErrorContainer = indigoDarkOnErrorContainer,
    background = indigoDarkBackground,
    onBackground = indigoDarkOnBackground,
    surface = indigoDarkSurface,
    onSurface = indigoDarkOnSurface,
    surfaceVariant = indigoDarkSurfaceVariant,
    onSurfaceVariant = indigoDarkOnSurfaceVariant,
    outline = indigoDarkOutline,
    inverseOnSurface = indigoDarkInverseOnSurface,
    inverseSurface = indigoDarkInverseSurface,
    inversePrimary = indigoDarkInversePrimary,
    surfaceTint = indigoDarkSurfaceTint,
    outlineVariant = indigoDarkOutlineVariant,
    scrim = indigoDarkScrim,
)
