package ir.thatsmejavad.backgroundable.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val middle_red_light_primary = Color(0xFF9A4520)
private val middle_red_light_onPrimary = Color(0xFFFFFFFF)
private val middle_red_light_primaryContainer = Color(0xFFFFDBCE)
private val middle_red_light_onPrimaryContainer = Color(0xFF370E00)
private val middle_red_light_secondary = Color(0xFF77574B)
private val middle_red_light_onSecondary = Color(0xFFFFFFFF)
private val middle_red_light_secondaryContainer = Color(0xFFFFDBCE)
private val middle_red_light_onSecondaryContainer = Color(0xFF2C160D)
private val middle_red_light_tertiary = Color(0xFF685F30)
private val middle_red_light_onTertiary = Color(0xFFFFFFFF)
private val middle_red_light_tertiaryContainer = Color(0xFFF1E3A8)
private val middle_red_light_onTertiaryContainer = Color(0xFF211B00)
private val middle_red_light_error = Color(0xFFBA1A1A)
private val middle_red_light_errorContainer = Color(0xFFFFDAD6)
private val middle_red_light_onError = Color(0xFFFFFFFF)
private val middle_red_light_onErrorContainer = Color(0xFF410002)
private val middle_red_light_background = Color(0xFFFFFBFF)
private val middle_red_light_onBackground = Color(0xFF201A18)
private val middle_red_light_surface = Color(0xFFFFFBFF)
private val middle_red_light_onSurface = Color(0xFF201A18)
private val middle_red_light_surfaceVariant = Color(0xFFF5DED6)
private val middle_red_light_onSurfaceVariant = Color(0xFF53433E)
private val middle_red_light_outline = Color(0xFF85736D)
private val middle_red_light_inverseOnSurface = Color(0xFFFBEEEA)
private val middle_red_light_inverseSurface = Color(0xFF362F2C)
private val middle_red_light_inversePrimary = Color(0xFFFFB598)
private val middle_red_light_surfaceTint = Color(0xFF9A4520)
private val middle_red_light_outlineVariant = Color(0xFFD8C2BA)
private val middle_red_light_scrim = Color(0xFF000000)

private val middle_red_dark_primary = Color(0xFFFFB598)
private val middle_red_dark_onPrimary = Color(0xFF5A1C00)
private val middle_red_dark_primaryContainer = Color(0xFF7B2F0A)
private val middle_red_dark_onPrimaryContainer = Color(0xFFFFDBCE)
private val middle_red_dark_secondary = Color(0xFFE7BEAF)
private val middle_red_dark_onSecondary = Color(0xFF442A20)
private val middle_red_dark_secondaryContainer = Color(0xFF5D4035)
private val middle_red_dark_onSecondaryContainer = Color(0xFFFFDBCE)
private val middle_red_dark_tertiary = Color(0xFFD4C78E)
private val middle_red_dark_onTertiary = Color(0xFF383006)
private val middle_red_dark_tertiaryContainer = Color(0xFF4F471B)
private val middle_red_dark_onTertiaryContainer = Color(0xFFF1E3A8)
private val middle_red_dark_error = Color(0xFFFFB4AB)
private val middle_red_dark_errorContainer = Color(0xFF93000A)
private val middle_red_dark_onError = Color(0xFF690005)
private val middle_red_dark_onErrorContainer = Color(0xFFFFDAD6)
private val middle_red_dark_background = Color(0xFF201A18)
private val middle_red_dark_onBackground = Color(0xFFEDE0DC)
private val middle_red_dark_surface = Color(0xFF201A18)
private val middle_red_dark_onSurface = Color(0xFFEDE0DC)
private val middle_red_dark_surfaceVariant = Color(0xFF53433E)
private val middle_red_dark_onSurfaceVariant = Color(0xFFD8C2BA)
private val middle_red_dark_outline = Color(0xFFA08D86)
private val middle_red_dark_inverseOnSurface = Color(0xFF201A18)
private val middle_red_dark_inverseSurface = Color(0xFFEDE0DC)
private val middle_red_dark_inversePrimary = Color(0xFF9A4520)
private val middle_red_dark_surfaceTint = Color(0xFFFFB598)
private val middle_red_dark_outlineVariant = Color(0xFF53433E)
private val middle_red_dark_scrim = Color(0xFF000000)

val middleRedLightColors = lightColorScheme(
    primary = middle_red_light_primary,
    onPrimary = middle_red_light_onPrimary,
    primaryContainer = middle_red_light_primaryContainer,
    onPrimaryContainer = middle_red_light_onPrimaryContainer,
    secondary = middle_red_light_secondary,
    onSecondary = middle_red_light_onSecondary,
    secondaryContainer = middle_red_light_secondaryContainer,
    onSecondaryContainer = middle_red_light_onSecondaryContainer,
    tertiary = middle_red_light_tertiary,
    onTertiary = middle_red_light_onTertiary,
    tertiaryContainer = middle_red_light_tertiaryContainer,
    onTertiaryContainer = middle_red_light_onTertiaryContainer,
    error = middle_red_light_error,
    errorContainer = middle_red_light_errorContainer,
    onError = middle_red_light_onError,
    onErrorContainer = middle_red_light_onErrorContainer,
    background = middle_red_light_background,
    onBackground = middle_red_light_onBackground,
    surface = middle_red_light_surface,
    onSurface = middle_red_light_onSurface,
    surfaceVariant = middle_red_light_surfaceVariant,
    onSurfaceVariant = middle_red_light_onSurfaceVariant,
    outline = middle_red_light_outline,
    inverseOnSurface = middle_red_light_inverseOnSurface,
    inverseSurface = middle_red_light_inverseSurface,
    inversePrimary = middle_red_light_inversePrimary,
    surfaceTint = middle_red_light_surfaceTint,
    outlineVariant = middle_red_light_outlineVariant,
    scrim = middle_red_light_scrim,
)

val middleRedDarkColors = darkColorScheme(
    primary = middle_red_dark_primary,
    onPrimary = middle_red_dark_onPrimary,
    primaryContainer = middle_red_dark_primaryContainer,
    onPrimaryContainer = middle_red_dark_onPrimaryContainer,
    secondary = middle_red_dark_secondary,
    onSecondary = middle_red_dark_onSecondary,
    secondaryContainer = middle_red_dark_secondaryContainer,
    onSecondaryContainer = middle_red_dark_onSecondaryContainer,
    tertiary = middle_red_dark_tertiary,
    onTertiary = middle_red_dark_onTertiary,
    tertiaryContainer = middle_red_dark_tertiaryContainer,
    onTertiaryContainer = middle_red_dark_onTertiaryContainer,
    error = middle_red_dark_error,
    errorContainer = middle_red_dark_errorContainer,
    onError = middle_red_dark_onError,
    onErrorContainer = middle_red_dark_onErrorContainer,
    background = middle_red_dark_background,
    onBackground = middle_red_dark_onBackground,
    surface = middle_red_dark_surface,
    onSurface = middle_red_dark_onSurface,
    surfaceVariant = middle_red_dark_surfaceVariant,
    onSurfaceVariant = middle_red_dark_onSurfaceVariant,
    outline = middle_red_dark_outline,
    inverseOnSurface = middle_red_dark_inverseOnSurface,
    inverseSurface = middle_red_dark_inverseSurface,
    inversePrimary = middle_red_dark_inversePrimary,
    surfaceTint = middle_red_dark_surfaceTint,
    outlineVariant = middle_red_dark_outlineVariant,
    scrim = middle_red_dark_scrim,
)
