package ir.thatsmejavad.backgroundable.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val middleRedLightPrimary = Color(0xFF9A4520)
private val middleRedLightOnPrimary = Color(0xFFFFFFFF)
private val middleRedLightPrimaryContainer = Color(0xFFFFDBCE)
private val middleRedLightOnPrimaryContainer = Color(0xFF370E00)
private val middleRedLightSecondary = Color(0xFF77574B)
private val middleRedLightOnSecondary = Color(0xFFFFFFFF)
private val middleRedLightSecondaryContainer = Color(0xFFFFDBCE)
private val middleRedLightOnSecondaryContainer = Color(0xFF2C160D)
private val middleRedLightTertiary = Color(0xFF685F30)
private val middleRedLightOnTertiary = Color(0xFFFFFFFF)
private val middleRedLightTertiaryContainer = Color(0xFFF1E3A8)
private val middleRedLightOnTertiaryContainer = Color(0xFF211B00)
private val middleRedLightError = Color(0xFFBA1A1A)
private val middleRedLightErrorContainer = Color(0xFFFFDAD6)
private val middleRedLightOnError = Color(0xFFFFFFFF)
private val middleRedLightOnErrorContainer = Color(0xFF410002)
private val middleRedLightBackground = Color(0xFFFFFBFF)
private val middleRedLightOnBackground = Color(0xFF201A18)
private val middleRedLightSurface = Color(0xFFFFFBFF)
private val middleRedLightOnSurface = Color(0xFF201A18)
private val middleRedLightSurfaceVariant = Color(0xFFF5DED6)
private val middleRedLightOnSurfaceVariant = Color(0xFF53433E)
private val middleRedLightOutline = Color(0xFF85736D)
private val middleRedLightInverseOnSurface = Color(0xFFFBEEEA)
private val middleRedLightInverseSurface = Color(0xFF362F2C)
private val middleRedLightInversePrimary = Color(0xFFFFB598)
private val middleRedLightSurfaceTint = Color(0xFF9A4520)
private val middleRedLightOutlineVariant = Color(0xFFD8C2BA)
private val middleRedLightScrim = Color(0xFF000000)

private val middleRedDarkPrimary = Color(0xFFFFB598)
private val middleRedDarkOnPrimary = Color(0xFF5A1C00)
private val middleRedDarkPrimaryContainer = Color(0xFF7B2F0A)
private val middleRedDarkOnPrimaryContainer = Color(0xFFFFDBCE)
private val middleRedDarkSecondary = Color(0xFFE7BEAF)
private val middleRedDarkOnSecondary = Color(0xFF442A20)
private val middleRedDarkSecondaryContainer = Color(0xFF5D4035)
private val middleRedDarkOnSecondaryContainer = Color(0xFFFFDBCE)
private val middleRedDarkTertiary = Color(0xFFD4C78E)
private val middleRedDarkOnTertiary = Color(0xFF383006)
private val middleRedDarkTertiaryContainer = Color(0xFF4F471B)
private val middleRedDarkOnTertiaryContainer = Color(0xFFF1E3A8)
private val middleRedDarkError = Color(0xFFFFB4AB)
private val middleRedDarkErrorContainer = Color(0xFF93000A)
private val middleRedDarkOnError = Color(0xFF690005)
private val middleRedDarkOnErrorContainer = Color(0xFFFFDAD6)
private val middleRedDarkBackground = Color(0xFF201A18)
private val middleRedDarkOnBackground = Color(0xFFEDE0DC)
private val middleRedDarkSurface = Color(0xFF201A18)
private val middleRedDarkOnSurface = Color(0xFFEDE0DC)
private val middleRedDarkSurfaceVariant = Color(0xFF53433E)
private val middleRedDarkOnSurfaceVariant = Color(0xFFD8C2BA)
private val middleRedDarkOutline = Color(0xFFA08D86)
private val middleRedDarkInverseOnSurface = Color(0xFF201A18)
private val middleRedDarkInverseSurface = Color(0xFFEDE0DC)
private val middleRedDarkInversePrimary = Color(0xFF9A4520)
private val middleRedDarkSurfaceTint = Color(0xFFFFB598)
private val middleRedDarkOutlineVariant = Color(0xFF53433E)
private val middleRedDarkScrim = Color(0xFF000000)

val middleRedLightColors = lightColorScheme(
    primary = middleRedLightPrimary,
    onPrimary = middleRedLightOnPrimary,
    primaryContainer = middleRedLightPrimaryContainer,
    onPrimaryContainer = middleRedLightOnPrimaryContainer,
    secondary = middleRedLightSecondary,
    onSecondary = middleRedLightOnSecondary,
    secondaryContainer = middleRedLightSecondaryContainer,
    onSecondaryContainer = middleRedLightOnSecondaryContainer,
    tertiary = middleRedLightTertiary,
    onTertiary = middleRedLightOnTertiary,
    tertiaryContainer = middleRedLightTertiaryContainer,
    onTertiaryContainer = middleRedLightOnTertiaryContainer,
    error = middleRedLightError,
    errorContainer = middleRedLightErrorContainer,
    onError = middleRedLightOnError,
    onErrorContainer = middleRedLightOnErrorContainer,
    background = middleRedLightBackground,
    onBackground = middleRedLightOnBackground,
    surface = middleRedLightSurface,
    onSurface = middleRedLightOnSurface,
    surfaceVariant = middleRedLightSurfaceVariant,
    onSurfaceVariant = middleRedLightOnSurfaceVariant,
    outline = middleRedLightOutline,
    inverseOnSurface = middleRedLightInverseOnSurface,
    inverseSurface = middleRedLightInverseSurface,
    inversePrimary = middleRedLightInversePrimary,
    surfaceTint = middleRedLightSurfaceTint,
    outlineVariant = middleRedLightOutlineVariant,
    scrim = middleRedLightScrim,
)

val middleRedDarkColors = darkColorScheme(
    primary = middleRedDarkPrimary,
    onPrimary = middleRedDarkOnPrimary,
    primaryContainer = middleRedDarkPrimaryContainer,
    onPrimaryContainer = middleRedDarkOnPrimaryContainer,
    secondary = middleRedDarkSecondary,
    onSecondary = middleRedDarkOnSecondary,
    secondaryContainer = middleRedDarkSecondaryContainer,
    onSecondaryContainer = middleRedDarkOnSecondaryContainer,
    tertiary = middleRedDarkTertiary,
    onTertiary = middleRedDarkOnTertiary,
    tertiaryContainer = middleRedDarkTertiaryContainer,
    onTertiaryContainer = middleRedDarkOnTertiaryContainer,
    error = middleRedDarkError,
    errorContainer = middleRedDarkErrorContainer,
    onError = middleRedDarkOnError,
    onErrorContainer = middleRedDarkOnErrorContainer,
    background = middleRedDarkBackground,
    onBackground = middleRedDarkOnBackground,
    surface = middleRedDarkSurface,
    onSurface = middleRedDarkOnSurface,
    surfaceVariant = middleRedDarkSurfaceVariant,
    onSurfaceVariant = middleRedDarkOnSurfaceVariant,
    outline = middleRedDarkOutline,
    inverseOnSurface = middleRedDarkInverseOnSurface,
    inverseSurface = middleRedDarkInverseSurface,
    inversePrimary = middleRedDarkInversePrimary,
    surfaceTint = middleRedDarkSurfaceTint,
    outlineVariant = middleRedDarkOutlineVariant,
    scrim = middleRedDarkScrim,
)
